CREATE TABLE dns_id_counter_v4 (id INT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE dns_id_counter_v6 (id INT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB;
INSERT INTO dns_id_counter_v4 VALUES (0);
INSERT INTO dns_id_counter_v6 VALUES (0);

CREATE TABLE dns_records_ipv4 (
    id        INT UNSIGNED NOT NULL PRIMARY KEY,
    domain    VARCHAR(255) NOT NULL UNIQUE KEY,
    ipv4      VARCHAR(15) NOT NULL,
    timestamp INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE dns_records_ipv6 (
    id        INT UNSIGNED NOT NULL PRIMARY KEY,
    domain    VARCHAR(255) NOT NULL UNIQUE KEY,
    ipv6      VARCHAR(39) NOT NULL,
    timestamp INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
